### ISSUE TITLE
Link to PearAI Server is broken

### ISSUE THREAD

**Issue by jamesmurdza** [trypear/pearai-master#1]
The link goes to:

https://github.com/trypear/pearai-server/tree/61fc5622c91cf194df241f66d2ef6699a12b7f89

**Comment by Fryingpannn** [comment]
Yup, the server repo is not viewable on purpose. See the `README.md`.

> [pearai-server](https://github.com/trypear/pearai-server): this is the server of PearAI which is semi-private to maintain security. The use of PearAI server is optional, and serves as a way to provide convenience for users who do not wish to use their own API keys.

The server repo is mostly private for now, and only top contributors (around 10~) of the PearAI project may get access. It is this way in order to prevent bad actors from abusing vulnerabilities in the server. For the security of the users, it's better that the server is abstracted. After all, it isn't necessary to run the app.
